# Generated by Django 5.1.2 on 2024-10-10 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_blogpost_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
